### ISSUE TITLE
Bug in init.js

### ISSUE THREAD

**Issue by dfrownfelter** [firstpr/yarn#2]
There's a bug in ../commands/init.js! Follow the guide in the readme. Run the test suite and see if you can find the bug. Good luck!

**Comment by vincegando** [comment]
Can I take this one?

**Comment by Rayhatron** [comment]
I'd like to work on this.

**Comment by dfrownfelter** [comment]
Cool @Rayhatron it's yours. Let me know if you have any questions!

**Comment by dfrownfelter** [comment]
@Rayhatron we changed the name of the organization so update your remote with `git remote set-url upstream https://github.com/firstpr/yarn.git` to complete the pull request.

**Comment by Rayhatron** [comment]
Updated remote.
